// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	gcp "gcp-rider/gcp"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchInstances provides a mock function with given fields: ctx, projectID
func (_m *Client) FetchInstances(ctx context.Context, projectID string) ([]gcp.Instance, error) {
	ret := _m.Called(ctx, projectID)

	var r0 []gcp.Instance
	if rf, ok := ret.Get(0).(func(context.Context, string) []gcp.Instance); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gcp.Instance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}